### ISSUE TITLE
MDHT artifactory link

### ISSUE THREAD

**Issue by PeterTeunissen** [onc-healthit/reference-ccda-validator#190]
Hello,

The pom.xml of this project points to an http url for an artifactory instance to provide the MDHT libraries.

Is there a reason that these libraries would not be uploaded to maven central (https://mavenrepository.com) by the producer, so that when we build, we can rely on the jars not having been manipulated (like contain viruses) and we can retrieve them over https?

Thanks,
  Peter

**Comment by austinmoody** [comment]
Added to Jira (SITE-3967) will try to get some background/answer.

**Comment by austinmoody** [comment]
From Sean: "We do not have control over some of the eclipse jars and plugins and they are historically not available on the central site 
As such we have not pursued having MDHT on the central site - this was a process completed numerous years ago 
Pushing to maven central is not out of the question."

Have entered a backlog ticket for this for now, not sure of timeline.
