### ISSUE TITLE
Modifying the listener port

### ISSUE THREAD

**Issue by jxfish2** [onc-healthit/reference-ccda-validator#58]
Is there a way to change the listener port?

Where could I set, or over-ride the default listener ports for the CCDA Validator?

Is there a single file?

Or would it need to be modified in multiple files?

**Comment by drbgfc** [comment]
You would update the Tomcat config:
For example: https://mkyong.com/tomcat/how-to-change-tomcat-default-port/
Let me know if this is not what you meant.
