### ISSUE TITLE
Validator throwing json error

### ISSUE THREAD

**Issue by mbowar** [onc-healthit/reference-ccda-validator#67]
After yesterdays release, when trying to upload a ccd to the validator we are now getting the following error. 
![image](https://user-images.githubusercontent.com/44811707/62139998-d7241d80-b2af-11e9-9c61-178c95948eeb.png)
![image](https://user-images.githubusercontent.com/44811707/62140029-e30fdf80-b2af-11e9-9ba1-52ae96abf322.png)

**Comment by mbowar** [comment]
@ssavarala Can you help please?

**Comment by drbgfc** [comment]
It's hard to say exactly at this point - but it looks like we had a DNS attack - I am restarting the server. Thanks for the notification!

**Comment by mbowar** [comment]
Thank you the issue is now resolved.




[cid:Experity_Branded_Email_Sig_16cfe429-0b3d-4df9-9d68-8da11216d59d.jpg]

Meghan Bowar
Enterprise Product Expert/Nurse
p: 605-789-6751


This email may contain privileged information. If received in error, please immediately delete, then notify the sender.
