### ISSUE TITLE
Error creating bean with name 'referenceCCDAValidationController'

### ISSUE THREAD

**Issue by LHAMPTON** [onc-healthit/reference-ccda-validator#82]
I've been working on this on and off for a while but have not been able to resolve it.  Looked at other similar issues but no one ever posted a final resolution.  Tried first with Tomcat 9, then backed up to Tomcat 7. I think/hope I finally have the correct file structure in place, but seems that no matter what I do, it continues to fail with the same exception - see the attached log file for all the details, but the bottom line seems to be:

Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

The Java runtime I'm using is 14.0.2 

When I searched the above exception, I found a post, found here

https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio

that might help me overcome this if I understood them well enough to follow, but I don't really speak "java" very well.

If I can get that resolved, perhaps it will tell me what, if any other, things are missing. Here's my setup:

All of this is running on my development machine.  The  folder/file structure looks like this:

![image](https://user-images.githubusercontent.com/2256330/98549496-dc209c80-2268-11eb-9bba-3fae8f27de48.png)

I've attached a copy of my Tomcat 7\apache-tomcat-7.0.106\conf\Catalina\localhost\referenceccdaservice.xml file, but I think I have the links within it setup as needed. (Had to give it a .txt extension in order to attach it here.)
[referenceccdaservice.xml.txt](https://github.com/onc-healthit/reference-ccda-validator/files/5510973/referenceccdaservice.xml.txt)

The only things that I know I'm missing are the codes for the ADA and CPT code systems; but I see no direct indication that this is failing for lack of those files. (It failed in the same way before I had the correct directory structure underneath the code_repository directory.)
[referenceccdaservice.2020-11-07.log](https://github.com/onc-healthit/reference-ccda-validator/files/5510951/referenceccdaservice.2020-11-07.log)

Thanks for your help.

**Comment by drbgfc** [comment]
Hi,

It may take time for one of us to get to this issue. But, I can add it to our board. 

I think your issue is your JDK version. If it's not your entire issue, it is at least one of them. We have never tested with JDK 8 and 7. Any version newer than those I would definitely not expect to work due to modules. Is there any reason you can't install JDK 8 (https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html) or 7 (https://www.oracle.com/java/technologies/javase/javase7-archive-downloads.html)? I would try 8 first.

Thanks,
Dan

**Comment by LHAMPTON** [comment]
I gave up on Java 14 and installed Java 7.  No longer getting that error and things start, more or less correctly.  I have another issue but I'll post it as a new thread.
