### ISSUE TITLE
Validator fails to load HCPCS folder

### ISSUE THREAD

**Issue by LHAMPTON** [onc-healthit/reference-ccda-validator#83]
I have our code_repository folder setup with the structure described in the documentation.  After manually creating a couple of the files, most of it loads correctly... with these exceptions:

If I include the HCPCS folder, the loader fails with:
 Failed to load configured vocabulary directory.
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'HCPCS' is defined

So, either the bean is missing, or I have the wrong name for the folder... which is it?

Also, the Code Systems spreadsheet says that the ICD9CM_DX folder should contain a fixed-length file.  When I tried that, it failed with:
09:49:47,520 INFO  [VocabularyLoadRunner:44] Loading files in : ICD9CM_DX...
09:49:47,522 ERROR [VocabularyLoadRunner:107] Failed to load configured vocabulary directory.
java.lang.StringIndexOutOfBoundsException: String index out of range: 5

I opened the spreadsheet version of the file and saved it as tab-delimited and it loaded correctly.

Thanks

**Comment by drbgfc** [comment]
Thanks.
I will make a ticket for this and try to ensure it doesn't take too long to address.
Once the issue is resolved, if there are errors in the documentation, we will update them.

**Comment by Plow74** [comment]
I know this is an old ticket, but after review, there is no loader in the current codebase to load this code system. The team will review this gap and determine if it's a feature to be implemented.

**Comment by Plow74** [comment]
The team has determined that this feature is not critical for certification and will not be implemented at this time.
